#define CAVE_SPAWN_MOB "mob"
#define CAVE_SPAWN_FEATURE "feature"
#define CAVE_SPAWN_TENDRIL "tendril"
#define CAVE_SPAWN_MEGAFAUNA "megafauna"

///This datum handles the transitioning from a turf to a specific biome, and handles spawning decorative structures and mobs.
/datum/biome
	/// Type of turf this biome creates for open turfs
	var/open_turf_type
	/// Type of turf this biome creates for closed turfs
	var/closed_turf_type
	/// Chance of having a structure from the flora types list spawn
	var/flora_density = 0
	/// Chance of spawning special features, such as geysers.
	var/feature_density = 0
	/// Chance of having a mob from the fauna types list spawn
	var/fauna_density = 0
	/// Weighted list of type paths of flora that can be spawned when the
	/// turf spawns flora.
	var/list/flora_types = list()
	/// Weighted list of extra features that can spawn in the biome, such as
	/// geysers. Gets expanded automatically.
	var/list/feature_types = list()
	/// Weighted list of type paths of fauna that can be spawned when the
	/// turf spawns fauna.
	var/list/fauna_types = list()
	/// Weighted list of megafauna that can spawn from SPAWN_MEGAFAUNA fauna entry
	/// Defaults to GLOB.megafauna_spawn_list
	var/list/megafauna_types = null
	/// Radius around features within which we avoid spawning other features
	var/feature_exclusion_radius = 7
	/// Radius around mobs which we avoid spawning other mobs
	var/mob_exclusion_radius = 12
	/// Radius around megafauna within which we avoid spawning tendrils
	var/megafauna_exclusion_radius = 7
	/// Minimum distance between tendril spawns
	var/tendril_exclusion_radius = 12

/datum/biome/New()
	. = ..()
	if(length(flora_types))
		flora_types = expand_weights(fill_with_ones(flora_types))

	if(length(fauna_types))
		fauna_types = expand_weights(fill_with_ones(fauna_types))

	if(length(feature_types))
		feature_types = expand_weights(feature_types)

	if(isnull(megafauna_types))
		megafauna_types = GLOB.megafauna_spawn_list

///This proc handles the creation of a turf of a specific biome type
/datum/biome/proc/generate_turf(turf/gen_turf, closed)
	if (closed)
		gen_turf.ChangeTurf(closed_turf_type, null, CHANGETURF_DEFER_CHANGE)
		return

	gen_turf.ChangeTurf(open_turf_type, null, CHANGETURF_DEFER_CHANGE)

	if(length(flora_types) && prob(flora_density))
		var/obj/structure/flora = pick(flora_types)
		new flora(gen_turf)
		return

	if(length(feature_types) && prob(feature_density))
		var/atom/picked_feature = pick(feature_types)
		new picked_feature(gen_turf)
		return

	if(length(fauna_types) && prob(fauna_density))
		var/mob/fauna = pick(fauna_types)
		new fauna(gen_turf)


/// This proc handles the creation of a turf of a specific biome type, assuming
/// that the turf has not been initialized yet. Don't call this unless you know
/// what you're doing.
/datum/biome/proc/generate_turf_for_terrain(turf/gen_turf, closed)
	var/turf_type = closed ? closed_turf_type : open_turf_type
	var/turf/new_turf = new turf_type(gen_turf)
	return new_turf


/**
 * This proc handles the sequential creation of turfs of a specific biome type
 * in order to optimize the generation for large amount of turfs.
 *
 * Arguments:
 * * gen_turfs - List of turfs to use for turf generation.
 *
 * Returns a new list of turfs that were generated by the biome.
 */
/datum/biome/proc/generate_turfs_for_terrain(list/turf/gen_turfs)
	var/list/turf/new_turfs = list()

	for(var/turf/gen_turf as anything in gen_turfs)
		var/closed = gen_turfs[gen_turf]
		var/turf_type = closed ? closed_turf_type : open_turf_type
		var/turf/new_turf = new turf_type(gen_turf)
		new_turfs[new_turf] = turf_type

		if(gen_turf.turf_flags & NO_RUINS)
			new_turf.turf_flags |= NO_RUINS

		CHECK_TICK

	return new_turfs


/**
 * This proc handles populating the given turfs based on whether flora, features
 * and fauna are allowed. Does not take megafauna into account.
 *
 * Does nothing if `flora_allowed`, `features_allowed` and `fauna_allowed` are
 * `FALSE`, or if there's no flora, feature or fauna types for the matching
 * allowed type. Aka, we return early if the proc wouldn't do anything anyway.
 */
/datum/biome/proc/populate_turfs(list/turf/target_turfs, flora_allowed, features_allowed, fauna_allowed)
	var/has_flora = flora_allowed && length(flora_types)
	var/has_features = features_allowed && length(feature_types)
	var/has_fauna = fauna_allowed && length(fauna_types)

	if(!has_flora && !has_features && !has_fauna)
		return

	// Assoc list of spawned categories to
	// Static as to be shared between all biomes
	var/static/list/spawn_data
	if (isnull(spawn_data))
		spawn_data = list(
			CAVE_SPAWN_FEATURE = list(),
			CAVE_SPAWN_TENDRIL = list(),
			CAVE_SPAWN_MOB = list(),
			CAVE_SPAWN_MEGAFAUNA = list(),
		)

	for(var/turf/target_turf as anything in target_turfs)
		// Only put stuff on open turfs we generated, so closed walls and rivers and stuff are skipped
		if(!istype(target_turf, open_turf_type))
			continue

		CHECK_TICK
		if (!(target_turf.turf_flags & TURF_BLOCKS_POPULATE_TERRAIN_FLORAFEATURES))
			if (flora_allowed && prob(flora_density))
				var/flora_type = pick(flora_types)
				new flora_type(target_turf)
				continue

			if (features_allowed && prob(feature_density))
				var/can_spawn = TRUE
				for(var/turf/spawn_turf as anything in spawn_data[CAVE_SPAWN_FEATURE])
					if (get_dist(spawn_turf, target_turf) <= feature_exclusion_radius)
						can_spawn = FALSE
						break

				if (can_spawn)
					var/picked_feature = pick(feature_types)
					new picked_feature(target_turf)
					spawn_data[CAVE_SPAWN_FEATURE] += target_turf
					continue

		if (!fauna_allowed || !prob(fauna_density))
			continue

		var/picked_mob = pick(fauna_types)
		var/is_megafauna = FALSE
		var/is_tendril = FALSE

		if (picked_mob == SPAWN_MEGAFAUNA)
			picked_mob = pick_weight(megafauna_types)
			is_megafauna = TRUE
		else
			is_tendril = ispath(picked_mob, /mob/living/basic/mining/tendril)

		var/can_spawn = TRUE
		if(is_tendril)
			for(var/turf/spawn_turf as anything in spawn_data[CAVE_SPAWN_TENDRIL])
				if (get_dist(spawn_turf, target_turf) <= tendril_exclusion_radius)
					can_spawn = FALSE
					break

			if (!can_spawn)
				continue

			// Also avoid spawning them next to megafauna
			for(var/turf/spawn_turf as anything in spawn_data[CAVE_SPAWN_MEGAFAUNA])
				if (get_dist(spawn_turf, target_turf) <= megafauna_exclusion_radius)
					can_spawn = FALSE
					break

		else if (is_megafauna)
			// Megafauna can spawn wherever it wants as long as its not next to another mega
			for(var/turf/spawn_turf as anything in spawn_data[CAVE_SPAWN_MEGAFAUNA])
				if (get_dist(spawn_turf, target_turf) <= megafauna_exclusion_radius)
					can_spawn = FALSE
					break
		else
			for(var/turf/spawn_turf as anything in spawn_data[CAVE_SPAWN_MOB])
				if (get_dist(spawn_turf, target_turf) <= mob_exclusion_radius)
					can_spawn = FALSE
					break

		if (!can_spawn)
			continue

		if (is_tendril)
			spawn_data[CAVE_SPAWN_TENDRIL] += target_turf
		else if (is_megafauna)
			spawn_data[CAVE_SPAWN_MEGAFAUNA] += target_turf
		spawn_data[CAVE_SPAWN_MOB] += target_turf

		var/mob/living/created = new picked_mob(target_turf)

		if (!is_tendril && !is_megafauna)
			var/obj/effect/mining_mob_respawner/respawner = new(target_turf)
			respawner.setup(fauna_types, created)

		// There can be only one Bubblegum, so don't waste spawns on it
		if(ispath(picked_mob, /mob/living/simple_animal/hostile/megafauna/bubblegum))
			megafauna_types.Remove(picked_mob)

			new picked_mob(target_turf)

// ============================================================================
// PLANETARY BIOMES FOR SUPERCRUISE PLANET GENERATION
// ============================================================================
// NOTE: These simple biomes are ONLY used for visual representation in supercruise.
// Actual planet generation uses detailed biomes from the individual biome files
// ============================================================================

/datum/biome/planet_asteroid
	open_turf_type = /turf/open/misc/asteroid
	closed_turf_type = /turf/closed/mineral/random
	flora_density = 5
	fauna_density = 0
	feature_density = 1
	flora_types = list(
		/obj/structure/flora/rock = 3,
		/obj/structure/flora/rock/pile = 1,
	)

/datum/biome/planet_ice
	open_turf_type = /turf/open/misc/asteroid/snow/icemoon
	closed_turf_type = /turf/closed/mineral/random
	flora_density = 8
	fauna_density = 0
	feature_density = 2
	flora_types = list(
		/obj/structure/flora/rock = 2,
		/obj/structure/flora/rock/pile = 2,
		/obj/structure/flora/grass/brown = 1,
		/obj/structure/flora/grass/both = 1,
	)

/datum/biome/planet_lava
	open_turf_type = /turf/open/misc/asteroid/basalt/lava_land_surface
	closed_turf_type = /turf/closed/mineral/volcanic
	flora_density = 10
	fauna_density = 0
	feature_density = 3
	flora_types = list(
		/obj/structure/flora/rock = 3,
		/obj/structure/flora/rock/pile = 2,
		/obj/structure/flora/bush = 2,
	)

/datum/biome/planet_jungle
	open_turf_type = /turf/open/floor/grass
	closed_turf_type = /turf/closed/mineral/random/jungle
	flora_density = 20
	fauna_density = 0
	feature_density = 5
	flora_types = list(
		/obj/structure/flora/tree/jungle = 5,
		/obj/structure/flora/bush = 4,
		/obj/structure/flora/grass/jungle = 3,
		/obj/structure/flora/grass/jungle/b = 3,
		/obj/structure/flora/rock = 1,
	)

/datum/biome/planet_desert
	open_turf_type = /turf/open/misc/beach/sand
	closed_turf_type = /turf/closed/mineral/random
	flora_density = 3
	fauna_density = 0
	feature_density = 1
	flora_types = list(
		/obj/structure/flora/rock = 3,
		/obj/structure/flora/rock/pile = 2,
		/obj/structure/flora/bush/grassy = 1,
	)

/datum/biome/planet_beach
	open_turf_type = /turf/open/misc/beach/sand
	closed_turf_type = /turf/closed/mineral/random
	flora_density = 6
	fauna_density = 0
	feature_density = 2
	flora_types = list(
		/obj/structure/flora/tree/palm = 1,
		/obj/structure/flora/bush/grassy = 2,
		/obj/structure/flora/rock = 3,
		/obj/structure/flora/grass/both = 2,
	)

/datum/biome/planet_grassland
	open_turf_type = /turf/open/floor/grass
	closed_turf_type = /turf/closed/mineral/random
	flora_density = 12
	fauna_density = 0
	feature_density = 3
	flora_types = list(
		/obj/structure/flora/grass/jungle = 3,
		/obj/structure/flora/grass/jungle/b = 3,
		/obj/structure/flora/bush = 2,
		/obj/structure/flora/bush/grassy = 2,
		/obj/structure/flora/tree/jungle = 1,
		/obj/structure/flora/rock = 1,
	)

/datum/biome/planet_wasteland
	open_turf_type = /turf/open/misc/asteroid
	closed_turf_type = /turf/closed/mineral/random
	flora_density = 15
	fauna_density = 0
	feature_density = 8
	flora_types = list(
		/obj/structure/flora/rock = 3,
		/obj/structure/flora/rock/pile = 2,
		/obj/structure/girder/displaced = 1,
	)

// ============================================================================
// CAVE BIOME BASE CLASS
// ============================================================================

/**
 * Cave biomes are special biomes that use cellular automata to create
 * natural cave systems with walls and floors.
 * The closed flag in gen_turfs[turf] determines if it's a wall or floor.
 */
/datum/biome/cave

/datum/biome/cave/planet_asteroid
	open_turf_type = /turf/open/misc/asteroid
	closed_turf_type = /turf/closed/mineral/random
	flora_density = 8
	fauna_density = 0
	feature_density = 2
	flora_types = list(
		/obj/structure/flora/rock = 4,
		/obj/structure/flora/rock/pile = 3,
	)

/datum/biome/cave/planet_ice
	open_turf_type = /turf/open/misc/asteroid/snow/icemoon
	closed_turf_type = /turf/closed/mineral/random
	flora_density = 10
	fauna_density = 0
	feature_density = 3
	flora_types = list(
		/obj/structure/flora/rock = 3,
		/obj/structure/flora/rock/pile = 3,
		/obj/structure/flora/grass/both = 2,
	)

/datum/biome/cave/planet_lava
	open_turf_type = /turf/open/misc/asteroid/basalt/lava_land_surface
	closed_turf_type = /turf/closed/mineral/volcanic
	flora_density = 12
	fauna_density = 0
	feature_density = 5
	flora_types = list(
		/obj/structure/flora/rock = 5,
		/obj/structure/flora/rock/pile = 4,
	)

/datum/biome/cave/planet_jungle
	open_turf_type = /turf/open/misc/dirt
	closed_turf_type = /turf/closed/mineral/random/jungle
	flora_density = 25
	fauna_density = 0
	feature_density = 8
	flora_types = list(
		/obj/structure/flora/bush = 5,
		/obj/structure/flora/grass/jungle = 4,
		/obj/structure/flora/grass/jungle/b = 4,
		/obj/structure/flora/rock = 2,
	)

/datum/biome/cave/planet_desert
	open_turf_type = /turf/open/misc/beach/sand
	closed_turf_type = /turf/closed/mineral/random
	flora_density = 5
	fauna_density = 0
	feature_density = 2
	flora_types = list(
		/obj/structure/flora/rock = 4,
		/obj/structure/flora/rock/pile = 3,
	)

/datum/biome/cave/planet_beach
	open_turf_type = /turf/open/misc/beach/sand
	closed_turf_type = /turf/closed/mineral/random
	flora_density = 8
	fauna_density = 0
	feature_density = 3
	flora_types = list(
		/obj/structure/flora/rock = 4,
		/obj/structure/flora/rock/pile = 2,
		/obj/structure/flora/grass/both = 2,
	)

/datum/biome/cave/planet_grassland
	open_turf_type = /turf/open/misc/dirt
	closed_turf_type = /turf/closed/mineral/random
	flora_density = 15
	fauna_density = 0
	feature_density = 4
	flora_types = list(
		/obj/structure/flora/grass/jungle = 3,
		/obj/structure/flora/grass/jungle/b = 3,
		/obj/structure/flora/rock = 3,
		/obj/structure/flora/bush = 2,
	)

/datum/biome/cave/planet_wasteland
	open_turf_type = /turf/open/misc/asteroid
	closed_turf_type = /turf/closed/mineral/random
	flora_density = 20
	fauna_density = 0
	feature_density = 10
	flora_types = list(
		/obj/structure/flora/rock = 3,
		/obj/structure/flora/rock/pile = 2,
		/obj/structure/girder/displaced = 2,
	)

#undef CAVE_SPAWN_MOB
#undef CAVE_SPAWN_FEATURE
#undef CAVE_SPAWN_TENDRIL
#undef CAVE_SPAWN_MEGAFAUNA
